config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),

    path("",include("crud.urls"))
]

crud/urls.py
from turtle import update
from django.urls import path
from .views import Create, Updateview, home,Detailview,Deleteview

app_name="crud"

urlpatterns = [
    path("",home,name="home"),
    path("create/",Create,name="create"),
    path("crud/<int:pk>/",Detailview, name='detail'),
    path('crud/<int:pk>/update',Updateview,name='update'),
    path('crud/<int:pk>/delete',Deleteview,name='delete')
]

crud/models.py
from django.db import models

# Create your models here.
class Detail(models.Model):
    accname=models.CharField(max_length=90)
    age=models.IntegerField()
    password=models.CharField(max_length=200)

    def __str__ (self):
        return f'accname{self.accname}'

crud/forms.py
from dataclasses import fields
from django.forms import ModelForm
from .models import  Detail


class Detailform(ModelForm):
    class Meta:
        model=Detail
        fields=['accname','age']

crud/views.py
from audioop import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from matplotlib.style import context
from .models import Detail
from .forms import Detailform
# Create your views here.


def home(request):
    user=Detail.objects.all()
    data={
        "user":user
    }
    return render (request,"home.html",data)



    #create in Crud

def Create(request):
    form=Detailform()
    if request.method=="POST":
        form=Detailform(request.POST)
        if form.is_valid():
            form.save()
            return redirect("crud:home")
    context={"form":form}
    return render (request ,"create.html",context)

def Detailview(request,id):
   
    user=Detail.objects.get(pk=id)
    context = {
        'user':user
    }
    return render(request, 'detail.html', context)

def Updateview(request,pk):
    user=get_object_or_404(Detail,pk=id)
    form=Detailform(instance=user)
    if request.method=="POST":
        form=Detailform(request.POST,instance=user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('crud:detail',kwargs={'pk',user.id}))

    context={
        'form':form
    }
    return render (request,"create.html",context)

def Deleteview(request,pk):
    user=get_object_or_404(Detail,pk=id)
    if request.method=="POST":
        user.delete()
        return HttpResponseRedirect(reverse('crud:home'))
    context={'user':user}
    return render (request,'delete.html',context)
        

crud/templates/create.html
{%extends 'main.html' %}
{% load bootstrap4 %}

{% load crispy_forms_tags %}
{%  block content  %}
<form method="POST" action="">
     {% csrf_token %}
     <h1>wewe</h1>
     {{form.accname|as_crispy_field}}
     {{form.age|as_crispy_field}}
     <button href="" type="submit">SUBMIT</button>
</form>

{% endblock content %}

crud/templates/delete.html
{% extends 'main.html' %}

{% block content %}
<h5>Are you sure you want to delete</h5><br>

<form action="" method="POST">{% csrf_token %}
    <button type="submit">Confirm</button>
    <button><a href="{% url 'crud:detail' users.id %}">No</a></button>
</form>


{% endblock %}

crud/templates/details.html
{%  extends 'main.html' %}



{% block content %}

<h1>please welcome to class room please</h1>
<a href="/">Home</a>
<div>
    <div>
        <h2>{{users.accname}}</h2>
        <a href="">{{users.age}}</a>
       <br>
       <p>{{ users.password }}</p>
       <br>
         <button><a href="{% url 'crud:update' users.id %}">Update</a></button>
        <button type="submit"><a href="{% url 'crud:delete' users.id %}">Delete</a></button>
    </div>
</div>

{% endblock %}

crud/templates/home.html
{% extends 'main.html' %}


{% block  content %}

<h1><a href="{% url 'crud:create' %} ">create</a></h1>
{%for users in user %}
{{users.accname}}
{{users.age}}
{{users.password}}
<h1 a=href"{% url 'crud:detail' users.id %}" ><a href="">Detail</a></h1>
{% endfor %}
{% endblock %}users in user

crud/templates/main.html
{% load  static  %} 
<html>
<head>
    <title>hello</title>
</head>
 <body>
          {%  block  content  %}
           
           {% endblock   %}
        
    </body>
<html>